# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='img_data.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0eimg_data.proto\"\\\n\x07ImgData\x12\x10\n\x08\x63lass_id\x18\x01 \x02(\x05\x12\x12\n\nclass_name\x18\x02 \x02(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\n\n\x02wh\x18\x04 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x0c')
)




_IMGDATA = _descriptor.Descriptor(
  name='ImgData',
  full_name='ImgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_id', full_name='ImgData.class_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_name', full_name='ImgData.class_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='ImgData.file_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wh', full_name='ImgData.wh', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ImgData.data', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ImgData'] = _IMGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgData = _reflection.GeneratedProtocolMessageType('ImgData', (_message.Message,), dict(
  DESCRIPTOR = _IMGDATA,
  __module__ = 'img_data_pb2'
  # @@protoc_insertion_point(class_scope:ImgData)
  ))
_sym_db.RegisterMessage(ImgData)


# @@protoc_insertion_point(module_scope)
